env_files = ["../.env"]
build_dir = "tmp"

[build]
  entrypoint = ["./tmp/main"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["migrations"]
  exclude_file = ["Dockerfile"]
  exclude_regex = ["_test.go"]

#[misc]
#  startup_banner = ""
